Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (click the restart button in the tool bar or select Kernel$\rightarrow$Restart in the menu bar) and then **run all cells** (in the menu bar, select Cell$\rightarrow$Run All).

**Make sure you delete `raise NotImplementedError()`** (if existing) and fill in any place that says "YOUR CODE HERE" or "YOUR ANSWER HERE", as well as your name below:

In [94]:
NAME = "Stephen Shell"

**Don't modify the formal TEST cells!**

---

# Numerical Python

In [95]:
# ALWAYS RUN THIS CELL FIRST
import numpy as np

### 1. Vector manipulation (0.5 points)

The word "vector" is commonly used to mean a one-dimensional array. 
Create a vector of size 10 called `vectorm` that contains zeros but with the fifth value as 2.

In [96]:
# YOUR CODE HERE
l1 = [0,0,0,0,2,0,0,0,0,0] 

vectorm = np.array(l1)
# raise NotImplementedError()

In [97]:
"""(0.5 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

assert isinstance(vectorm, np.ndarray)
assert vectorm[:4].all() == 0
assert vectorm[4] == 2
assert vectorm[5:].all() == 0

print("Success!")

Success!


### 2. Vector range (0.5 points)

Create a vector called `vectorr` with values ranging from 10 to 59, inclusive (aka, also including 10 and 59). Do not write out each element to create the array.

In [98]:
# YOUR CODE HERE
l2 = range(10,60)

vectorr = np.array(l2)
# raise NotImplementedError()

In [99]:
"""(0.5 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

assert np.array_equal(vectorr, np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]))
assert isinstance(vectorr, np.ndarray)

print("Success!")

Success!


### 3. Reverse a vector (1 point)

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element.

In [100]:
def reverse(vec):
    """return a 1D vector with the elements reversed

    Input
    -----
        x: 1D array

    Output
    ------
        res: 1D array, with the elements of `x` reversed
    """
    # YOUR CODE HERE
    rev = vec[::-1]
    return rev
    # raise NotImplementedError()

In [101]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

vec = np.array([1, 2, 3, 4])
vector_reversed = reverse(vec)
assert np.array_equal(vector_reversed, np.array([4, 3, 2, 1]))
vec = np.array([-1, 9, 2.38])
vector_reversed = reverse(vec)
assert np.array_equal(vector_reversed, np.array([2.38, 9, -1]))
assert isinstance(vector_reversed, np.ndarray)

print("Success!")

Success!


### 4. Array with random values (1 point)

Create a 10x20x3 array called `random_array` that contains normally distributed ($\mu=0,~\sigma=1)$ random values.

In [102]:
# YOUR CODE HERE
random_array = np.random.normal(0, 1, (10,20,3))
print(random_array)
# raise NotImplementedError()

[[[ 8.85085597e-02 -1.03271472e+00  4.03650862e-01]
  [ 2.25931673e-01  1.03675899e+00  4.28794080e-01]
  [ 7.26154683e-01  8.96652386e-01 -3.48933266e-01]
  [ 3.11211910e-01 -1.11900551e+00  4.32713940e-01]
  [ 2.28677926e+00  9.64103735e-01  3.98928417e-01]
  [-4.79727016e-01  1.93263601e+00 -1.27335335e+00]
  [-1.21340415e-01 -4.79892550e-01  7.49015557e-01]
  [ 8.74092243e-01 -1.39905033e+00 -7.33291890e-01]
  [ 1.33161355e+00  4.98530083e-01 -8.69637828e-01]
  [-8.20676382e-01  1.17897838e+00 -3.66181646e-02]
  [ 1.25882063e+00  1.34027192e+00 -3.15632649e-01]
  [-8.99711076e-01 -1.50551298e+00 -7.12626406e-01]
  [-5.82547917e-01  9.15886288e-01  5.46627999e-01]
  [ 9.31601072e-01  6.19109478e-01  1.55361634e+00]
  [-6.46759794e-01 -7.26991456e-02 -4.68067543e-01]
  [-2.91737952e-01 -8.13921594e-01 -9.31409616e-01]
  [-3.16786088e-01 -1.06115904e+00 -8.36516720e-01]
  [ 8.98146791e-01 -5.47234399e-01  4.19281808e-01]
  [-1.24652736e+00 -9.00890220e-01 -8.57205553e-01]
  [ 1.093785

In [103]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

assert random_array.shape == (10, 20, 3)  # check for shape
assert np.allclose(random_array.mean(), 0, atol=0.1)
assert np.allclose(random_array.std(), 1, atol=0.1)

print("Success!")

Success!


### 5. Vector without end points (1 point)

Create a vector of size 10 called `vector_end` which has values ranging uniformly in sequence from 0 to 1 (not random sampling), both excluded. Put it in another way, the 10 elements should be equally-spaced between 0 and 1 (as shown in the picture). Do not explicitly write out the values in an array. Instead, use `np.linspace` and modify the resultant vector by indexing.

![0-10-number.png](0-10-number.png)'

In [104]:
# YOUR CODE HERE
# l4 = [x/11 for x in range(1,11)]
# vector_end = np.array(l4)
vector_end = np.linspace(1/11, 1, num=10, endpoint=False, retstep=False)
print(vector_end)
# raise NotImplementedError()

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [105]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

output_vector_end = np.array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])
assert np.allclose(output_vector_end, vector_end)

print("Success!")

Success!


### 6. Sorted random vector (1 point)

Create a vector of size 20 called `sorted_array` which contains random numbers (from a function in `np.random`) that you have sorted. It should be sorted in increasing order.

In [106]:
# YOUR CODE HERE
arr = np.random.rand(20)
sorted_array = np.sort(arr)
# raise NotImplementedError()

In [107]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

# check data type
assert isinstance(sorted_array, np.ndarray)

# check for proper size
assert sorted_array.size == 20
# check that array is sorted
# note that instead of > 0, we should use >= 0!
assert (np.diff(sorted_array) >= 0).all()

print("Success!")

Success!


### 7. Operations on an array with random values (4 points)

Fill in the code for a function, `maxesmins()`, which takes in an array and then returns 
- the minimum value of the 2nd row
- the maximum value of the 4th column

If there aren't enough rows or columns in the array to return either, return `np.nan` instead.

Hint 1: use try-except might be the best approach here. But you can also use if-else to solve this problem.

Hint 2: Don't use K.shape >= (2, 4) as it will not work for comparing two values together at the same time


In [108]:
def maxesmins(K):
    """Returns the min of the 2nd row and max of the 4th column.

    Parameters
    ----------
    K : numpy array
        
    Returns
    -------
    min of the 2nd row and max of the 4th column, as a tuple, or a np.nan for either if the array is too small to calculate it
    """
    # YOUR CODE HERE
    try:
        arr_min = np.nanmin(K[1])
    except:
        arr_min = np.nan
        
    K_t = K.transpose()
    
    try:
        arr_max = np.nanmax(K_t[3])
    except:
        arr_max = np.nan
    return (arr_min, arr_max)
    # raise NotImplementedError()

In [109]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

L = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
assert (2, 8) == maxesmins(L)

print("This test worked! Next cell has more.")

This test worked! Next cell has more.


In [110]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

M = np.ones((5, 5))
assert (1, 1) == maxesmins(M)

print("This test worked! Next cell has more.")

This test worked! Next cell has more.


In [111]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run."""

N = np.zeros((3, 2))
assert (0, np.nan) == maxesmins(N)

print("Success!")

Success!


In [112]:
N = np.zeros((1, 3))
assert (np.nan, np.nan) == maxesmins(N)

print("Success!")

Success!


In [113]:
N = np.zeros((3, 1))
assert (0, np.nan) == maxesmins(N)

print("Success!")

Success!


### 8. array concatenation (3 points)

Write a function `array_concat(x, y)` that accepts x and y as two arrays and returns an array that concatenates array x and array y horizontally. It should work on both 1D arrays or 2D arrays (or mixture of 1D and 2D arrays) with the desirable shape. Below are some examples and your function should also work for arrays with different shapes than those examples.
    
    if (1D and 1D):
    x is array([1, 2, 3])
    y is array([4, 5])
    
    The returned array will be array([1, 2, 3, 4, 5])
    
    if (2D and 2D):
    x is array([[1, 2, 3],
                [4, 5, 6],
                [4, 5, 6]])
                
    y is array([[7, 8],
                [9, 10],
                [9, 10]])
    
    The returned array will be array([[1, 2, 3, 7, 8],
                                      [4, 5, 6, 9, 10],
                                      [4, 5, 6, 9, 10]])

    if (2D and 1D):
    x is array([[1, 2, 3],
                [4, 5, 6],
                [4, 5, 6]])
                
    y is array([7, 8, 9)])
    
    The returned array will be array([[1, 2, 3, 7],
                                      [4, 5, 6, 8],
                                      [4, 5, 6, 9]])
                                      
    if (1D and 2D):
    x is array([7, 8)])
                
    y is array([[1, 2, 3],
                [4, 5, 6]])
    
    The returned array will be array([[7, 1, 2, 3],
                                      [8, 4, 5, 6]])

In [114]:
def array_concat(x, y):
    """input two arrays x and y and join the two arrays horizontally
       return the concatenated array

    Inputs:
        x: array
        y: array
    
    Returns:
        the concatenated array
    """
    
    # YOUR CODE HERE
    if x.ndim == y.ndim:
        return np.hstack((x, y))
    return [np.hstack((x1, y1)) for x1, y1 in zip(x, y)]
    # raise NotImplementedError()

In [115]:
# part A
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

x = np.array([2, 3, 4])
y = np.array([4, 5])
assert np.array_equal(array_concat(x, y), np.array([2, 3, 4, 4, 5]))

print("Success!")

Success!


In [116]:
# part B
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

x = np.array([[1, 4], [2, 3]])
y = np.array([2, 3])
assert np.array_equal(array_concat(x, y), np.array([[1, 4, 2], [2, 3, 3]]))

print("Success!")

Success!


In [117]:
# part C
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

x = np.array([[1, 4, 3], [2, 3, 1]])
y = np.array([[2, 3, 3], [1, 4, 1]])
assert np.array_equal(array_concat(x, y), np.array([[1, 4, 3, 2, 3, 3], [2, 3, 1, 1, 4, 1]]))

print("Success!")

Success!


# Graduate student problems below

### 9. Convert from Cartesian to polar coordinates (3 points)

Write a function `cart2polar(xy)` which takes in an Nx2 (N rows and 2 columns) matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix (**also Nx2, not 2xN**). Read the docstring for more details. Note, you should use `np.arctan2` instead of `np.arctan` to preserve the correct quadrant.

In [118]:
def cart2polar(xy):
    """Convert input from Cartesian to polar coordinates.
    
    Parameters
    ----------
    xy : array
        Nx2 array of Cartesian coordinates, with columns of x and y coordinates, respectively.
        
    Returns
    -------
    rphi : array
        Coordinates Nx2 array containing input coordinates in polar representation, 
        with columns radius and angle, respectively.
    """
    # YOUR CODE HERE
    raise NotImplementedError()

In [119]:
"""(3 points) Test code for the previous function. This cell should NOT give any errors when it is run."""

cart = np.random.rand(10, 2)
polar = cart2polar(cart)

assert polar.shape == (10, 2)  # check for shape

test_input = np.array([[1, 0]])
test_output = np.array([[1, 0]])
assert (cart2polar(test_input) == test_output).all()  #  check for known case [1, 0]

test_input = np.array([[0, 1]])
test_output = np.array([[1, np.pi/2]])
assert (cart2polar(test_input) == test_output).all()  #  check for known case [0, 1]

print("Success!")

NotImplementedError: 